apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    # don't change nodePort value or type of port without
    # adapting port (strg-f MINIKUBE_IP) in the srcs/mysql/srcs/wp.sql file
    nodePort: 30505
