# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ftps
#   labels:
#     app: ftps
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 300Mi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:v1
        imagePullPolicy: Never
        ports:
          - containerPort: 20
            hostPort: 20
          - containerPort: 21
            hostPort: 21
          - containerPort: 21100
            hostPort: 21100
          - containerPort: 21101
            hostPort: 21101
          - containerPort: 21102
            hostPort: 21102
          - containerPort: 21103
            hostPort: 21103
          - containerPort: 21104
            hostPort: 21104
      #   volumeMounts:
      #     - name: ftps-data
      #       mountPath: /ftps
      # volumes:
      #   - name: ftps-data
      #     persistentVolumeClaim:
      #       claimName: ftps
