apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      targetPort: 20
      name: whytho
      protocol: TCP
    - port: 21
      targetPort: 21
      name: connect
      protocol: TCP
    - port: 21100
      targetPort: 21100
      name: psv0
      protocol: TCP
    - port: 21101
      targetPort: 21101
      name: psv1
      protocol: TCP
    - port: 21102
      targetPort: 21102
      name: psv2
      protocol: TCP
    - port: 21103
      targetPort: 21103
      name: psv3
      protocol: TCP
    - port: 21104
      targetPort: 21104
      name: psv4
      protocol: TCP
