apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      name: why
    - port: 21
      name: connect
    - port: 31100
      name: psv0
    - port: 31101
      name: psv1
    - port: 31102
      name: psv2
    - port: 31103
      name: psv3
    - port: 31104
      name: psv4
    - port: 31105
      name: psv5
