apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: NodePort
  ports:
    - port: 20
      targetPort: 20
      name: whytho
      protocol: TCP
    - port: 21
      targetPort: 21
      name: connect
      protocol: TCP
    - port: 21100
      targetPort: 21100
      name: psv0
      protocol: TCP
    - port: 21101
      targetPort: 21101
      name: psv1
      protocol: TCP
