apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          # env:
          #   - name: PMA_HOST
          #     value: mysql-svc
          #   - name: PMA_PORT
          #     value: "3306"
          # envFrom:
          #   - secretRef:
          #     name: mysql-secrets
          volumeMounts:
            - name: phpmyadmin-config
              subPath: config.inc.php
              mountPath: /usr/share/webapps/phpmyadmin/config.inc.php
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: phpmyadmin-config
        configMap:
          name: phpmyadmin
