apiVersion: v1
kind: Secret
metadata:
  name: grafana
  labels:
    app: grafana
type: Opaque
stringData:
  GF_INSTALL_PLUGINS: grafana-piechart-panel, blackmirror1-singlestat-math-panel
  GF_SECURITY_ADMIN_PASSWORD: password

