apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: services
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: services
    spec:
      containers:
      - image: mysql:v1
        name: mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
        securityContext:
          privileged: true
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
