apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: services
spec:
  selector:
    app: services
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      name: http
